spring:
  application:
    name: prismaflow
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DATABASE:prismaflow}
      username: ${MONGO_USER:admin}
      password: ${MONGO_PASS:admin123}
      authentication-database: ${MONGO_AUTH_DB:admin}

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

